<?php
$email_domains=array(
'@gmail.com','@avontech.com','@yourdomain.com','@hotmail.com','@hotmail.co.uk','@hotmail.fr','@msn.com','@yahoo.fr','@wanadoo.fr','@orange.fr','@comcast.net','@yahoo.co.uk','@yahoo.com.br',
'@yahoo.co.in','@live.com',
'@rediffmail.com','@free.fr',
'@web.de','@gmx.de','@ymail.com',
'@libero.it',
'@outlook.com',
'@uol.com.br',
'@bol.com.br',
'@cox.net',
'@hotmail.it', 
'@sbcglobal.net',
'@sfr.fr',
'@live.fr',
'@verizon.net',
'@live.co.uk'
);